name: Pipeline

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black
    - name: Analysing the code with black
      run: |
        black --check .

  pytest:
    runs-on: ubuntu-latest
    needs: [pylint, black]
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
      - name: Run pytest
        run: |
          pytest --html=report/python${{ matrix.python-version }}/report.html --self-contained-html
      - name: Upload pytest report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          if-no-files-found: error
          overwrite: true
          path: report/python${{ matrix.python-version }}/

  upload_report:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Upload pytest report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          if-no-files-found: error
          overwrite: true
          path: report/
